version: '3.7'

services:
#  mariadb:
  symfony-demo2_mariadb:
    container_name: symfony-demo2_mariadb_1
    image: bianjp/mariadb-alpine:latest
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
