version: '3.7'

services:
#  mysql:
  project_mysql:
    container_name: project_mysql_1
    image: bianjp/mariadb-alpine:latest
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    labels:
    - db.network.tunnel.hostname=project_db_host
